### ISSUE TITLE
Rotate files reaching a max size

### ISSUE THREAD

**Issue by jibin-tj** [darrylwest/simple-node-logger#11]
Hi

I am unable to rotate files reaching a max size in same day itself. I am unable to open log files because the size is too huge

**Comment by darrylwest** [comment]
you could try creating hourly logs rather than daily.  There is an example in the "examples" folder.  All you need to do is add hours to the date format like this: 'YYYY.MM.DD-HH'

**Comment by jibin-tj** [comment]
Thank you darrylwest
