### ISSUE TITLE
Line breaks on Windows

### ISSUE THREAD

**Issue by matthew-dean** [darrylwest/simple-node-logger#12]
In Windows, the log file entries are all on one line. I assume it doesn't have line breaks that are readable in Windows? Or is there another option to set?

**Comment by matthew-dean** [comment]
I assume it's this line: https://github.com/darrylwest/simple-node-logger/blob/master/lib/FileAppender.js#L40

For Notepad support (Windows standard), this should be `\r\n`.

**Comment by darrylwest** [comment]
fixed with latest version...
