### ISSUE TITLE
How to configure rolling logger to remove log files older than X number of days?

### ISSUE THREAD

**Issue by codeowl1** [darrylwest/simple-node-logger#16]
Hi there,

Thanks for your great work on the simple node logger and sharing the code!!

Is it possible to configure rolling logger to remove log files older than X number of days?

Regards,

Scott

**Comment by darrylwest** [comment]
I don't have an integrated purge method so I've been using cron to clean-up old logs.  I will consider an integrated purger in the future; thanks for your support...

**Comment by serdarde** [comment]
This is an ancient topic, but I would like to share a nice solution for the ones who have the same feature:

You can use [find-remove ](https://www.npmjs.com/package/find-remove) package.

    const findRemoveSync = require('find-remove');

    findRemoveSync(logfilePath, {
      age: { seconds: 3600 },
      extensions: '.log',
    });
