### ISSUE TITLE
Remove auto createConsoleAppender from createLogManager

### ISSUE THREAD

**Issue by rottmann** [darrylwest/simple-node-logger#19]
https://github.com/darrylwest/simple-node-logger/blob/master/lib/SimpleLogger.js#L319-L322

I want to use the console and rollingFile.
The console should be formated with an own formatter, but this is not possible, when auto create the consoleAppender with createLogManager

**Comment by rottmann** [comment]
I want to colorize the console output depending on the LogLevel.

**Comment by rottmann** [comment]
I manually set now the appenders and create my own ColoredConsoleAppender.

```
  let appenders = [
    new ColoredConsoleAppender(),
    manager.createRollingFileAppender({
      errorEventName: 'error',
      logDirectory: logPath,
      fileNamePattern: '<DATE>.log',
      dateFormat:'YYYYMMDD'
    })
  ]

  let logger = manager.createLogger()
  logger.setAppenders(appenders)
```

**Comment by seeARMS** [comment]
Can you share your ColoredConsoleAppender?
