### ISSUE TITLE
[Feature Request] Pretty Printing Objects

### ISSUE THREAD

**Issue by rmwxiong** [darrylwest/simple-node-logger#25]
It would be cool if there was a built in option to print out objects using nicely formatted JSON with newlines. Maybe there's a library that does just that?

**Comment by darrylwest** [comment]
If you look in lib/AbstractAppender.js  the formatObject() method attempts to determine if the log message is an object and, if it is, tries to stringify it.  It also tries to do an inspect on values that render [object Object], so the pretty print is close.   The current implementation just does a straight stringify but a small modification could do stringify( value, true, 2 ) to get a pretty print.  Is that what you are looking for?

**Comment by rmwxiong** [comment]
Yup! That sounds like it. Instead of a straight stringify it would be awesome to pass in an option somehow to do the pretty print

**Comment by darrylwest** [comment]
I can merge once the formatting is fixed (line 95), 4 spaces.  thanks...

**Comment by darrylwest** [comment]
fixed for verion 93.42
