### ISSUE TITLE
Can I have timestamp too in the fileNamePattern when using RollingFilelogger

### ISSUE THREAD

**Issue by challapruthvi** [darrylwest/simple-node-logger#3]
Now I am able to put in DATE format as a filenamepattern. But, i really want timestamp to be included in the filename pattern. is it possible ??

**Comment by darrylwest** [comment]
yes, for the simple-file-logger but no for the rolling logger.  rolling uses the date format to determine when to roll, so a timestamp would roll each minute--probably not what you want.
