### ISSUE TITLE
[Question] Override FileAppender formatEntry

### ISSUE THREAD

**Issue by seriousfunk** [darrylwest/simple-node-logger#33]
How would I go about overriding FileAppender? Thanks for your help :)

This doesn't work but shows what I'm trying to do.
```
const log = snl.createSimpleLogger(logFile)

log.appenders['FileAppender'].formatter = function(entry) {
  const fields = appender.formatEntry( entry );
  fields[2] = stripAnsi(fields[2]);
  fields.push( newline );
  return fields.join( appender.separator );
};
```

**Comment by darrylwest** [comment]
I wouldn't try to override a current appender.  You might try removing the FileAppender then adding a new one with the overrides that you want.  A better way is to create a LogManager and add appenders that you build. (see how snl.createSimpleLogger() works for an example)
