### ISSUE TITLE
Issue with rolling log files

### ISSUE THREAD

**Issue by thehexabyte** [darrylwest/simple-node-logger#39]
Hey, I don't know if I'm doing this wrong, but I'm trying to add a date to the file name with the rolling log files feature and it crashes. Here's the log error and code:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\logs\log-2018.10.29:19:40:57.
log'
```

```js
var date = new Date();
// create a rolling file logger based on date/time that fires process events
const opts = {
    errorEventName:'error',
    logDirectory:'/logs', // NOTE: folder must exist and be writable...
    fileNamePattern:`log-<DATE>:${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}.log`,
    dateFormat:'YYYY.MM.DD'
};
const logfiles = require('simple-node-logger').createRollingFileLogger( opts );
```

**Comment by thehexabyte** [comment]
Ok so stupid mistake on my point, I forgot to add a period to the folder path, but I thill get this error.
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\Code\Bots\HexaBot\logs\log-20
18.10.29:19:45:20.log'
```

**Comment by saru2020** [comment]
After lots of struggle, finally, I simply followed the examples and got it working.


> const opts = {
    domain:'Domain-A',
    logDirectory: __dirname + '../../../logfiles',
    fileNamePattern: 'hourly-test-<date>.log',
    dateFormat:'YYYY.MM.DD-HH'
};

> const log = require('simple-node-logger').createRollingFileLogger( opts );
