### ISSUE TITLE
Massive version change?

### ISSUE THREAD

**Issue by glenndehaan** [darrylwest/simple-node-logger#45]
Is it correct that the last version is like 18 mayor versions later?
<img width="761" alt="schermafbeelding 2019-01-04 om 10 15 02" src="https://user-images.githubusercontent.com/7496187/50681118-8cd50980-100a-11e9-8c65-4eb5a05c0bf6.png">

**Comment by timmo001** [comment]
I'd also like to know this. Is there a reason behind the major version change?

**Comment by wopian** [comment]
Looks like semantic versioning has been broken as it appears to be the date the version was published (YY.MM.DD)

**Comment by darrylwest** [comment]
I agree.  this probably wasn't fully vetted, but there are no breaking changes.  I'll be more careful to follow versioning rules going forward.
