### ISSUE TITLE
How to log to both Rolling File and stdout 

### ISSUE THREAD

**Issue by boygiandi** [darrylwest/simple-node-logger#52]
I'm using this from your README . But this only log to file, how to log to stdout at the same time ?

> // create a rolling file logger based on date/time that fires process events
> const opts = {
> 	errorEventName:'error',
>         logDirectory:'/mylogfiles', // NOTE: folder must exist and be writable...
>         fileNamePattern:'roll-<DATE>.log',
>         dateFormat:'YYYY.MM.DD'
> };
> const log = require('simple-node-logger').createRollingFileLogger( opts );

**Comment by darrylwest** [comment]
you can add an appender, but you need to reference the log manager; see the last example from the README.  Something like this:

const opts = {
    logDirectory:'/mylogfiles',
    fileNamePattern:'roll-<DATE>.log',
    dateFormat:'YYYY.MM.DD'
};
const manager = require('simple-node-logger').createLogManager();
manager.createConsoleAppender();
manager.createRollingFileAppender(opts);

const log = manager.createLogger('my-class');

**Comment by rahilwazir** [comment]
You don't need a `manager.createConsoleAppender();` by default `.createLogManager()` checks if there no logging interface it creates a console logger by default.
Otherwise it creates duplicate logs in console. Similar issue: https://github.com/darrylwest/simple-node-logger/issues/17
