### ISSUE TITLE
[object Object] in rolling logger log files

### ISSUE THREAD

**Issue by betweenbrain** [darrylwest/simple-node-logger#9]
Hello,

I am attempting to use your module to log all requests in a simple Node.js application. I have the logger set up as:

```
var opts = {
    logDirectory: __dirname + '/log',
    fileNamePattern: 'transactions-<DATE>.log',
    dateFormat: 'YYYY.MM.DD'
};

var log = require('simple-node-logger').createRollingFileLogger(opts);
```

and am logging requests with:

```
app.use(
    function (req, res, next) {
        log.info(req.originalUrl);
        next();
    }
);
```

The resulting log files contain `[object Object]`, like `13:34:30.703 INFO  [object Object] /`.

Simple file logger entries do not contain `[object Object]`. I tested with:

```
var log = require('simple-node-logger').createSimpleFileLogger('project.log');
```

with resulting entries to be like `13:39:26.030 INFO  /`

Any thoughts on what object the rolling file logger is adding to the entries?

**Comment by skyeyefront** [comment]
This is a bug. You can find the 'path/to/simple-node-logger/lib/SimpleLogger.js' file, and change the code like this:
`this.createLogger = function(category, level) {
        var logger;
  
        var opts = Object.prototype.toString.call(category) === '[object String]' ? options : dash.merge({}, options, category);
        // opts.category  = category ? category : opts.category; // remove it
        // opts.level     = level ? level : opts.level || dfltLevel; // remove it
        opts.appenders = appenders;
        
        logger = new Logger( opts );
        loggers.push( logger );
        
        return logger;
    };
`

**Comment by skyeyefront** [comment]
Or you can:
`var log = require('simple-node-logger').createLogManager(opts).createLogger()`

**Comment by betweenbrain** [comment]
Fantastic, thank you very much! I hope to be able to create a pull request
to address this as soon as I have time.

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/

**Comment by amarn** [comment]
I made a pull request with a simple fix.

**Comment by jibin-tj** [comment]
I am also having this issue. Thank you for the help.

Also , is there any way we can append a unique id per request .This will be helpful to debug in case of concurrent requests.

**Comment by jmklotz** [comment]
This issue seems to still exist today. I had to manually comment out the lines as suggested by skyeyefront.

**Comment by darrylwest** [comment]
New version is now in place.  Thanks for fixing this...
